/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "cwdcffqjaxkgnwalkuei"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3ZGNmZnFqYXhrZ253YWxrdWVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk4NDg0MTgsImV4cCI6MjA5NTQyNDQxOH0.vuP-yUmtibUtn8VPcNeF5mWa-aa2Lzb52Kuz4TkM-aU"